class CompilerTest{
public static void main(String[] args){
	int var=1+3;
	int var1 = 3;
	System.out.println(var1+var);
}}